# Generated by Django 4.0.2 on 2022-03-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='creator_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='bid_user',
            new_name='user',
        ),
    ]
