# Generated by Django 4.0.2 on 2022-03-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_new_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='current_bid',
            new_name='starting_bid',
        ),
    ]
